version: '3.5'

services:
  traefik:
    image: traefik:1.7
    command:
      - --api
      - --docker
      - --docker.domain=traefik.local
      - --docker.exposedByDefault=false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    networks:
      - reverse-proxy

networks:
  reverse-proxy:
    name: reverse-proxy